### ISSUE TITLE
Support for framework choice

### ISSUE THREAD

**Issue by vy0b0x** [intellifactory/websharper.visualstudio#3]
I can't select framework to .net core when i create project with this template, the only choice is .net framework 4.6.1
VS 2017 version: 15.7.6

**Comment by Tarmil** [comment]
Hi, the VS project templates have been moved to the [templates](https://github.com/dotnet-websharper/templates) repository. We should probably indicate that in the README here.

There is already [a feature request for .NET Core support](https://github.com/dotnet-websharper/templates/issues/14) there, I suggest you watch that :)

**Comment by vy0b0x** [comment]
Thanks.
